/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSkillsIndexRouteImport } from './routes/_authenticated/skills.index'
import { Route as AuthenticatedSkillsActivityRouteImport } from './routes/_authenticated/skills.$activity'
import { Route as AuthenticatedGameSubjectTopicRouteImport } from './routes/_authenticated/game.$subject.$topic'
import { Route as AuthenticatedLearnSubjectIndexRouteImport } from './routes/_authenticated/learn.$subject.index'
import { Route as AuthenticatedLearnSubjectTopicRouteImport } from './routes/_authenticated/learn.$subject.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsIndexRoute =
  AuthenticatedSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillsActivityRoute =
  AuthenticatedSkillsActivityRouteImport.update({
    id: '/skills/$activity',
    path: '/skills/$activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameSubjectTopicRoute =
  AuthenticatedGameSubjectTopicRouteImport.update({
    id: '/game/$subject/$topic',
    path: '/game/$subject/$topic',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnSubjectIndexRoute =
  AuthenticatedLearnSubjectIndexRouteImport.update({
    id: '/learn/$subject/',
    path: '/learn/$subject/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnSubjectTopicRoute =
  AuthenticatedLearnSubjectTopicRouteImport.update({
    id: '/learn/$subject/$topic',
    path: '/learn/$subject/$topic',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills/$activity': typeof AuthenticatedSkillsActivityRoute
  '/skills/': typeof AuthenticatedSkillsIndexRoute
  '/game/$subject/$topic': typeof AuthenticatedGameSubjectTopicRoute
  '/learn/$subject/$topic': typeof AuthenticatedLearnSubjectTopicRoute
  '/learn/$subject/': typeof AuthenticatedLearnSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills/$activity': typeof AuthenticatedSkillsActivityRoute
  '/skills': typeof AuthenticatedSkillsIndexRoute
  '/game/$subject/$topic': typeof AuthenticatedGameSubjectTopicRoute
  '/learn/$subject/$topic': typeof AuthenticatedLearnSubjectTopicRoute
  '/learn/$subject': typeof AuthenticatedLearnSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skills/$activity': typeof AuthenticatedSkillsActivityRoute
  '/_authenticated/skills/': typeof AuthenticatedSkillsIndexRoute
  '/_authenticated/game/$subject/$topic': typeof AuthenticatedGameSubjectTopicRoute
  '/_authenticated/learn/$subject/$topic': typeof AuthenticatedLearnSubjectTopicRoute
  '/_authenticated/learn/$subject/': typeof AuthenticatedLearnSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assessment'
    | '/dashboard'
    | '/learning'
    | '/progress'
    | '/settings'
    | '/skills/$activity'
    | '/skills/'
    | '/game/$subject/$topic'
    | '/learn/$subject/$topic'
    | '/learn/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assessment'
    | '/dashboard'
    | '/learning'
    | '/progress'
    | '/settings'
    | '/skills/$activity'
    | '/skills'
    | '/game/$subject/$topic'
    | '/learn/$subject/$topic'
    | '/learn/$subject'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assessment'
    | '/_authenticated/dashboard'
    | '/_authenticated/learning'
    | '/_authenticated/progress'
    | '/_authenticated/settings'
    | '/_authenticated/skills/$activity'
    | '/_authenticated/skills/'
    | '/_authenticated/game/$subject/$topic'
    | '/_authenticated/learn/$subject/$topic'
    | '/_authenticated/learn/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/': {
      id: '/_authenticated/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof AuthenticatedSkillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/$activity': {
      id: '/_authenticated/skills/$activity'
      path: '/skills/$activity'
      fullPath: '/skills/$activity'
      preLoaderRoute: typeof AuthenticatedSkillsActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game/$subject/$topic': {
      id: '/_authenticated/game/$subject/$topic'
      path: '/game/$subject/$topic'
      fullPath: '/game/$subject/$topic'
      preLoaderRoute: typeof AuthenticatedGameSubjectTopicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$subject/': {
      id: '/_authenticated/learn/$subject/'
      path: '/learn/$subject'
      fullPath: '/learn/$subject/'
      preLoaderRoute: typeof AuthenticatedLearnSubjectIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$subject/$topic': {
      id: '/_authenticated/learn/$subject/$topic'
      path: '/learn/$subject/$topic'
      fullPath: '/learn/$subject/$topic'
      preLoaderRoute: typeof AuthenticatedLearnSubjectTopicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillsActivityRoute: typeof AuthenticatedSkillsActivityRoute
  AuthenticatedSkillsIndexRoute: typeof AuthenticatedSkillsIndexRoute
  AuthenticatedGameSubjectTopicRoute: typeof AuthenticatedGameSubjectTopicRoute
  AuthenticatedLearnSubjectTopicRoute: typeof AuthenticatedLearnSubjectTopicRoute
  AuthenticatedLearnSubjectIndexRoute: typeof AuthenticatedLearnSubjectIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillsActivityRoute: AuthenticatedSkillsActivityRoute,
  AuthenticatedSkillsIndexRoute: AuthenticatedSkillsIndexRoute,
  AuthenticatedGameSubjectTopicRoute: AuthenticatedGameSubjectTopicRoute,
  AuthenticatedLearnSubjectTopicRoute: AuthenticatedLearnSubjectTopicRoute,
  AuthenticatedLearnSubjectIndexRoute: AuthenticatedLearnSubjectIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
